# Site settings
baseurl = "/" # To test in developement, add baseurl = http://localhost:8000/ run hugo to create the public site, then go to /public and start python -m SimpleHTTPServer 8000. https://tezos.com/
languageCode = "en"
title = "Tezos Foundation"
theme = "hugo-artist-mod-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Tezos Foundation"
	description = "A new digital commonwealth"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "contact@tezos.ch"


	# Header an navigation
	#
	# To change the header background the 'hero-bg-jpg' at 'static/img'.
	# Do the same with the logo ('logo.svg').
	# But keep the original filename!
	[params.header]
		title = "Tezos Foundation"
		shortBio = "A new digital commonwealth"

	# About section
	#
	# Replace the 'avatar.jpg' under 'static/img' with your own image.
	[params.about]
		title = "Tezos Foundation"
		bio = "The Tezos Foundation promotes the development of the Tezos blockchain and smart contracting platform, as well as related technologies and applications, and a vibrant ecosystem of developers and users."     
        secondtitle = "About us"
    Highlights = "<p>Tezos is a security-minded, future-proof, smart contract platform. It features a built-in governance mechanism that gives stakeholders the power to make decisions on protocol upgrades which are automatically pushed on the blockchain. In addition, Tezos features a proof-of-stake consensus algorithm and a smart contract language designed to facilitate formal verification. This ensures that changes to the software happen in a safe, secure, and transparent way without the risk of hard forks.</p><p>With a protocol written in OCaml and a new smart contract language called Michelson, Tezos makes security and nonambiguity our top concern.</p><p>For more information please review our:</p>- [White paper](https://github.com/tezos/tezos)<br>- [Position paper](https://tezos.com/pdf/position_paper.pdf)<br>- [Reddit](https://www.reddit.com/r/tezos/)"


	# Contact secion
	[params.contact]
		title = "Contact"

		# The following social network icons are available:
		# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
		# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
		[[params.contact.social]]
			icon = "twitter"
			link = "//twitter.com/tez0s"

		[[params.contact.social]]
			icon = "slack"
			link = "//slack.tezos.com/"

		[[params.contact.social]]
			icon = "github"
			link = "//github.com/tezos/tezos"



	[params.form]
		title = "Let's work together"
		# Form fields
		name = "Your Name"
		email = "Your Email"
		message = "Tell me about your project"
		buttonText = "Send"


	[params.footer]
		copyright = "© 2017 Tezos Foundation. Powered by: Appernetic.io"
